### ISSUE TITLE
Hi, miss

### ISSUE THREAD

**Issue by reliablesoftdev** [ellen-simonyan/ellen-simonyan#2]
Thank you for your interest to me.
https://discord.gg/dm4q7JEw
https://join.skype.com/invite/vzg2ZVxId1QE

You can get to me via these channels, I think we can be good friend each other.

**Comment by codelover1226** [comment]
> Thank you for your interest to me. https://discord.gg/dm4q7JEw https://join.skype.com/invite/vzg2ZVxId1QE
> 
> You can get to me via these channels, I think we can be good friend each other.

Excuse me who are you?

**Comment by codelover1226** [comment]
> Thank you for your interest to me. https://discord.gg/dm4q7JEw https://join.skype.com/invite/vzg2ZVxId1QE
> 
> You can get to me via these channels, I think we can be good friend each other.

Where are you from?

**Comment by reliablesoftdev** [comment]
I am Horea Bota from Moldova, I just wanted to get a friendship with you after I see you in JavaScript community organization.

**Comment by codelover1226** [comment]
Thank you.
I am from united states.
Where are you from?

**Comment by codelover1226** [comment]
I mean are you living in moldova now?

**Comment by codelover1226** [comment]
> https://discord.gg/dm4q7JEw



> I am Horea Bota from Moldova, I just wanted to get a friendship with you after I see you in JavaScript community organization.

Thank you
